// Shared anatomical landmarks, with articulated contours for each pose.
// Edit this source, never the generated SVGs.
const root = new URL("../src/", import.meta.url);
const anatomy = {
  // Continuous outer palm, plain wrist, rounded thenar/thumb transition.
  // Every upper contour ends at the same little-finger base (39, 25).
  lower: "C39 31 36.5 34.5 33 38V41Q33 42 32 42H23Q22 42 22 41V38C18.5 35.5 15.5 32 12.5 28C10.5 25.5 10 23 12 22C14 21 15.5 23 17 26",
  outline: 2.5,
};
const poses = {
  // Index extends from the radial side of the palm; the remaining knuckles fold.
  hover: "M17 26C18 22 18 18 18 14V10C18 6 24 6 24 10V20C24.5 16.5 29 16.5 29.5 20C30 17.5 34 18 34.5 21C36 19 39 20 39 23V25",
  // Arched MCP line; tapered, slightly splayed fingers and shallow rounded webs.
  grab: "M17 26C17.5 23 16.5 18 15.5 14C14.5 10 19.5 8.5 21 12L23 19C23.5 19.8 24 19.5 24 18L23.5 9C23.3 5 28.8 4.7 29 8.7L29.5 18C29.5 19.5 30.5 19.5 31 18L32 12C32.6 8.5 37.5 9.2 37 13L36 22C36 23 37 23 37.5 22L39 18C40.2 15 44 16.5 43 19.7L39 25",
  // Flexed fingers form a compact rounded mass; not shortened open fingers.
  grabbing: "M17 26L16 22C14.8 17.5 19.5 15 22 18C22 14.5 27 13.5 29 17C30 14.5 35 15.5 35 19C37 17 40 19 40 22L39 25",
};
for (const [name, upper] of Object.entries(poses)) {
  const d = upper + anatomy.lower + "Z";
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">
  <!-- Generated by scripts/generate-hands.ts; silhouette carries the anatomy. -->
  <path d="${d}" fill="#C5C7C5" stroke="#050505" stroke-linejoin="round" stroke-linecap="round" stroke-width="${anatomy.outline}"/>
</svg>\n`;
  const file = new URL(`${name}.svg`, root);
  if (process.argv.includes("--check")) {
    if (await Bun.file(file).text() !== svg) throw new Error(`${name}: generated SVG is stale; run make hands`);
  } else {
    await Bun.write(file, svg);
  }
}
// A separate silhouette plate removes color, labels inside the shapes and details.
if (!process.argv.includes("--check")) {
  const silhouettes = Object.entries(poses).map(([name, upper], index) =>
    `<g transform="translate(${32 + index * 192} 40)"><path d="${upper + anatomy.lower}Z" transform="scale(3)" fill="#050505"/><text x="72" y="158" text-anchor="middle" font-family="sans-serif" font-size="16">${name}</text></g>`).join("");
  await Bun.write(new URL("../silhouettes.svg", root),
    `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="256" viewBox="0 0 640 256"><rect width="640" height="256" fill="#eee"/>${silhouettes}</svg>\n`);
}
